.github/workflows/ci.yaml
main.go

pget has a problem that it needs to download everything into memory along each of the different parallel connections before finally saving everything to disk.  This has two consequences:
- pget needs to consume at least as much memory as the size of the downloaded file
- pget cannot begin writing to disk until all the bytes have been downloaded from source
I had a thought that we could precreate a sparse file of the correct length by using the os.Truncate(size) call.  Then each goroutine can write to different offsets within the same file, in parallel.
I tested this locally on macOS and I was able to download a 308MB file with pget's memory usage only reaching 26MB.
This commit is a WIP because I've commented out the untar stuff to keep the proof of concept simple.  We should restore (or …

WIP: use less memory by downloading to sparse file

---

.github/workflows/ci.yaml
main.go

Reverts replicate/pget#9
This makes `pget -x` much slower. We should investigate if we can fix that before committing to the sparse file implementation

Revert "WIP: use less memory by downloading to sparse file"

---

.github/workflows/ci.yaml
Makefile
README.md
script/build

This PR updates `Makefile` to follow the conventions used by Cog and the Replicate CLI, and updates the README and CI to use `make` for building the project exclusively. This PR also updates the README to provide instructions for [installing with Homebrew](https://github.com/replicate/homebrew-tap/pull/6) on macOS.

Add instructions for installing with Homebrew and building from source

---

go.mod
go.sum
main.go

* Add sleep jitter for retries
* Add backoff with formula: 2^retryNum * 500ms, maximum 5000ms
* Add configurable (CLI) retries `-r` cli option
* Retries will include the `Pget-Retry-Count` header indicating the retry number

Retry Improvements

---

main.go

currently, each chunk has to wait for storagebouncer to do its thing and follows redirects. it's faster to follow the redirect once and use that url subsequently 
HEAD also needs retry logic but that's for another time

only follow redirect once

---

main.go

- limit concurrency for small files
- potentially let others know how many pgets are running

handle small files better

---

main.go
pkg/config/config.go
pkg/download/buffer.go
pkg/download/modes.go
pkg/download/tar_extraction.go

Add the download mode framework with `buffer` and `tar-extract` to start. This allows us to expand the modes we want to operate in without impacting defaults or other users.

Implement Download modes

---

cmd/multifile/multifile.go
pkg/client/client.go
pkg/client/clientpool.go
pkg/download/buffer.go
pkg/download/modes.go

This is a refactoring of the client pooling:
* move away from global variables towards a dedicated ClientPool interface
* move away from global config (code in pkg/ shouldn't be making viper.Get* calls)
* make ClientPool responsible for acquiring and releasing clients, hiding it behind the standard Do() interface
* get rid of UserAgentTransport, now that we wrap Do() we can set User-agent there
* create client pools per scheme://host on demand, not up front.  This requires some funky work with a RWMutex so please review this carefully!

Refactor client pool

---

README.md
cmd/multifile/multifile.go
cmd/multifile/multifile_test.go
cmd/root/root.go
main.go
pkg/cli/common_test.go
pkg/client/client.go
pkg/config/config.go
pkg/config/config_test.go
pkg/download/buffer.go
pkg/download/modes.go
pkg/download/modes_test.go
pkg/download/tar_extraction.go
pkg/extract/tar.go
pkg/logging/log.go
pkg/version/version_test.go

* Do not call Viper for the sake of calling Viper
* Remove Globals for Modes
* Set MaxConnPerHost for 0 when root cmd is run
* Improve Mode Factories
* Isolate MaxRetries and pass down instead of using Viper in client code
* Improve Download Metrics (and eliminate globals)
* Implement Tests for EnsureDestinationNotExist
* Implement Tests for config module
* Remove global Logger in Config
* Implement testing for version module
* Fix flaky test

More cleanup

---

pkg/download/buffer_slow_test.go
pkg/download/buffer_test.go

This adds a test (based on an in-memory filesystem) and a few benchmarks (based on synthetic files created in a temp dir, and one real file in GCS).
Slow benchmarks are guarded by a `slow` build tag; they will only run if you add `--tags=slow` to your `go test` invocation.

Test and benchmark downloading

---

cmd/multifile/multifile.go
cmd/multifile/multifile_test.go
cmd/root/root.go
main.go
pkg/download/buffer.go
pkg/download/buffer_test.go
pkg/download/modes.go
pkg/download/tar_extraction.go

Cleanup context (pass it through from root) and remove useless option related to max concurrent files. We do not need to leverage the errgroup to limit the number of downloads any longer. We're using MaxConnPerHost to do this.

Cleanup context

---

cmd/multifile/multifile.go
cmd/root/root.go
pkg/config/config.go

There is no need to store the value(s) in a reachable config object as we use Viper to extract values. This removes the unneeded config-global-vars.

Do not use <X>Var or <X>VarP in config

---

cmd/root/root.go
pkg/cli/common.go
pkg/download/consistent_hashing.go

`downloadOpts` is passed by value into download.GetConsistentHashingMode (or any of the get...Mode functions). This means that populating CacheHosts after calling `getConsistentHashingMode` never initialized the values.

BUGFIX: Correct order of downloadOpts population

---

cmd/root/root.go
pkg/extract/tar.go
pkg/extract/tar_test.go

Fix tar extraction:
* Make -x function again for rootCMD
* Properly handle hard-links in tar files.
* implement testing for the tar extraction code
Closes: #87
Closes: #86

BUGFIX: Fix tar extraction

---

cmd/root/root.go

rootCMD was changed (erroneously) to use a PreRunE not a PersistentPreRunE that caused --resolve and -v to be properly handled. This meant multifile could not rely on --resolve or -v for anything useful (they were never "set" from multifile's perspective)
Closes: #95

BUGFIX: ensure --resolve and -v work in multifile mode

---

cmd/multifile/multifile.go
cmd/root/root.go

This change allows multifile to specify consumer(s). This is useful for things such as utilizing multifile with a null consumer for testing.
Closes: #100

BUGFIX: Multifile did not respect/utilize the consumer setting cli option

---

cmd/multifile/multifile.go
cmd/root/root.go

Multifile MUST support consistent-hashing mode. This is a copy/paste from the rootCMD override of the getter.Downloader; we should DRY this eventually.
Closes: #98

Implement consistent-hashing for multifile

---

cmd/root/root.go

We do not support .tar.gz fix the help to be explicit about what we support.
Closes: #113

BUGFIX: example in -x is incorrect

---

.github/workflows/ci.yaml
.goreleaser.yaml
Makefile

Use goreleaser insead of `ncipollo/release-action@v1`
Closes: #109

Migrate to GoReleaser

---

pkg/consistent/consistent.go
pkg/consistent/consistent_test.go
pkg/download/consistent_hashing.go
pkg/download/consistent_hashing_test.go

This implements a retry policy to consistently retry another host within the SRV set if we get a failure talking to the original host.
We still use the original fallback strategy if this retry fails. (Should we?)

Consistent hashing: consistently retry another host

---

cmd/cmd.go
cmd/root/root.go
cmd/version/version.go
pkg/cli/pid.go

* Do not block on pidfile when using the version command
* Emit warnings when blocking on pid file flock.
Closes: #124

Improve PID locking wait

---

cmd/multifile/multifile.go
cmd/root/root.go
pkg/config/config.go
pkg/config/config_test.go
pkg/config/optnames.go
pkg/download/consistent_hashing.go
pkg/download/consistent_hashing_test.go
pkg/download/options.go

Make domains to cache configurable via ENV. The implements the framework to also limit caching to certain prefixes to the path.

Make Domains to Cache configurable

---

.goreleaser.yaml

This PR updates the goreleaser config, and should solve two issues:
- Remove trailing whitespace in ilename which was causing goreleaser to prepend `default.` to some asset names. See https://github.com/goreleaser/goreleaser/issues/4513#issuecomment-1875312372
- Capitalize OS names like `Darwin` and `Linux` so you can use `uname -s` to construct OS-specific download URLs.
cc @anotherjesse

Fix goreleaser asset name template

---

pkg/download/buffer.go
pkg/download/consistent_hashing.go
pkg/download/consistent_hashing_test.go

We have a bug where:
- the file to download fits inside a single slice
- it takes N chunks to download
- N full chunks is larger than a slice
This was causing a logic error, but our error handling was failing to propagate the error correctly, so it manifested to the user as the last request not being made and the file being truncated.  In extract mode, this resulted in an unexpected EOF.
This PR fixes the error propagation so it would have been clearer that this was an internal pget bug, and it also fixes the bug.
This is a short PR but it's still worth reviewing commit-by-commit.

slice boundary bug

---

cmd/root/root.go

Do not hide --pid-file option from the help page
Partial: #128

Unhide --pid-file option

---

pkg/config/config.go
pkg/config/config_test.go

This restores to the status quo before #127.

Restore default cacheable URL prefix

---

README.md

This PR adds a cURL command for downloading an OS-specific binary.
DO NOT MERGE until we've cut a new release with the rectified filenames. See #139

document how to install binaries from GitHub

---

pkg/download/consistent_hashing.go

Based upon how bytes.Buffer works, it will continue to grow the underlying slice while reading data and add additional headroom to ensure that there is enough space, this means that when we allocate the bytes.Buffer to a small amount (minChunkSize()) the growth occurs regularly on any reads that push beyond the initial slice. Even at a minChunkSize of ~150M, when downloading SDXL we end up with a balloon of an additional ~10GiB allocated.
This has resulted in SigKill (OOMKILL) of pget in lower-ram systems. This does not address the overall memory allocation requirements of pget, which still generally encompasses the entire file size. An additional pass will need to be done to ensure the consumer can read and the buffer can be GC'd to minimize overall memory allocation.
This only surfaced …

Fix Consistent-Hash Memory Leak

---

cmd/multifile/multifile.go
cmd/root/root.go
go.mod
go.sum
pkg/client/client.go
pkg/download/buffer_test.go
pkg/download/consistent_hashing_test.go
pkg/pget_test.go

Following [a comment by @nickstenning][1], it's his fault.
This changes most (not all) consistent-hash tests to use httpmock to mock out http requests.  This is helpful because standard httptest uses random ports to listen on, which changes URL hash values and messes up the resulting consistent hash behaviour. It's also helpful because I can rewrite some tests that relied on the existence or otherwise of URLs on the public internet.
client.Options has been updated to allow a caller to pass in a Transport; I've also made it clear which options are TransportOptions (and therefore will be ignored if the caller passes their own Transport).
I write a couple of helper functions:
- rangeResponder is an httpmock.Responder that understands http range requests and responds accordingly
- …

Improve consistent-hash testing with httpmock

---

cmd/root/root.go

Do not require 2 arguments when using null consumer.
Multifile manifest still requires a target. This is to maintain continuity in the manifest parsing code.
Closes: #102

Improve null consumer

---

cmd/multifile/manifest.go
cmd/multifile/manifest_test.go
cmd/multifile/multifile.go
pkg/client/client.go
pkg/client/client_test.go
pkg/pget.go
pkg/pget_test.go

Refactor the manifest to ensure that the order is guaranteed when downloading via multifile. Some future consumers will require guaranteed ordering. This also reduces complexity as the schemeHost is no longer needed.

Guarantee Order of Downloads in multifile mode

---

cmd/root/root.go

Fix the single arg null consumer to not need two arguments to avoid a panic. This was an oversight where the requireArgs was addressed but not the explicit args[1] slice lookup.

Fix single arg null consumer

---

pkg/download/buffer.go
pkg/download/buffered_reader.go
pkg/download/consistent_hashing.go

This is an alternative to #174.  The key differences are:
- we use sync.Pool to store *bytes.Buffer instances rather than bufferedReader instances
- we keep the ready channel instead of using sync.Cond
- we return the buffer to the pool in Read() rather than requiring an explicit Close()
Overall this changes fewer parts of the codebase and is (IMHO) simpler and easier to understand.

Reuse buffers used by bufferedReader

---

pkg/download/buffer.go
pkg/download/buffer_unit_test.go
pkg/download/buffered_reader.go
pkg/download/consistent_hashing.go
pkg/download/consistent_hashing_test.go
pkg/download/strategy.go
pkg/pget.go

Currently, we use an errgroup as a semaphore in buffer and consistent hash modes, but we never inspect the results of sem.Wait() to see if there were any errors. This results in errors being swallowed.
This implements Wait(), and uses it everywhere we call Fetch().  Now that we have it, we don't need to store errors on bufferedReader so we can get rid of that.

implement Wait() on Strategy to fetch remaining errors

---

pkg/download/buffer.go
pkg/download/buffered_reader.go
pkg/download/buffered_reader_test.go
pkg/download/common.go
pkg/download/consistent_hashing.go

This reimplements bufferedReader on top of bufio.Reader.
This doens't make the code shorter, but it delegates more complexity to standard library functions.  In particular, bufio.Reader:
- handles storing errors and passing them out via Read() where appropriate
- handles errors where a read would exceed the buffer size
Furthermore this commit removes any HTTP concerns from bufferedReader.  The downloadBody() function has been changed to a generic ReadFrom().
Stacked on #179.

reimplement bufferedReader on top of bufio.Reader

---

cmd/root/root.go
pkg/extract/tar.go

Check for the tar extract flag being set in PersistentPreRunE, this ensures that there is no out-of-order operation concerns such as setting the extractor *after* we already get and create the consumer.

Check Tar Extract enablement in PersistentPreRunE

---

cmd/root/root.go

Improve pidfile location for non-root users. Use XDG_RUNTIME_PATH if set.
Closes: #128

Improve pidfile location for non-root

---

.gitignore

Allowlisting gitignore is generally preferable to ensure extra files do not sneak in (autogenerated, e.g. IDE files).

Make .gitignore better

---

.goreleaser.yaml

Do not use snapshot.name_template in the .goreleaser.yaml use snapshot.version_template (non-deprecated)

use snapshot.version_template

---

.goreleaser.yaml
pkg/consumer/consumer.go
pkg/consumer/consumer_test.go
pkg/consumer/null.go
pkg/consumer/null_test.go
pkg/consumer/tar_extractor.go
pkg/consumer/tar_extractor_test.go
pkg/consumer/write_file.go
pkg/consumer/write_file_test.go
pkg/download/buffer_slow_test.go
pkg/download/buffer_test.go
pkg/pget.go

In the case where we have a scenario that results in fewer than expected bytes being read from the tar compression or fewer than expected bytes written from the file writer consumer, propagate an error to the main program and exit with non-success status.
Observed behavior shows that within the tar-extraction code path in certain circumstances a clean EOF is received by the tarReader and the archive is partially extracted. This generally presents as files missing in the destination directory.
New code paths expect the correct number of bytes to be read or it will propagate a non-zero exit.

Error when too few bytes are read

---

.tool-versions
cmd/multifile/multifile.go
cmd/root/root.go
go.mod
pkg/config/config.go
pkg/config/optnames.go
pkg/download/buffer.go
pkg/download/consistent_hashing.go

Support specifying a cache endpoint for pget to utilize. This is
distinct from the CH mode as we do not need SRV records, a static target
is sufficient.
Using the standard PROXY env variables will result in non-pget traffic
being redirected. The Cache should be explicitly opt-in.

Imeplement Cache Support in BufferMode

---

pkg/download/buffer.go
pkg/download/buffer_unit_test.go
pkg/download/consistent_hashing.go
pkg/download/consistent_hashing_test.go

Recently had some issues with `pget` failing for smaller files because they did not respond with `content-range`. Checking [docs](https://developer.mozilla.org/en-US/docs/Web/HTTP/Reference/Headers/Content-Range), it looks like there isn't an expectation that `content-range` is provided when the full file is returned along with a `200 OK`. `pget` should handle `200 OK`s without `content-range`.
Unit tests added to test behavior.

Handle full file response

---

pkg/download/buffer.go
pkg/download/consistent_hashing.go
pkg/pget_test.go

Due to a misunderstanding in regex, I thought the value here would be a 0 indexed value. However, it is a 1 indexed value, so there was no need to do the subtraction by 1 that I put in here. This caused an off by 1 error when trying to write the file.
Added a unit test for this. If you try to run this unit test with the old version of this code, you should see the error
```
--- FAIL: TestDownloadSmallFileWith200 (0.01s)
/pget/pkg/pget_test.go:149: 
Error Trace:	/pget/pkg/pget_test.go:149
Error:      	Received unexpected error:
error writing file: expected 27 bytes, wrote 28
Test:       	TestDownloadSmallFileWith200
```

Fix off by 1 error

---

cmd/root/root.go
pkg/client/client.go
pkg/config/optnames.go

- **Revert "Rename --auth-token to --auth-header"**
- **Revert "Add --auth-token"**
This needs some rethinking. In most cases we shouldn't pass auth header if the original URL is redirected to an pre-signed URL. In that case some CDN will respond 400 or 403, plus we risk leaking the token.

Revert auth header changes

---

pkg/download/buffer.go

We need to retain query parameters when we redirect to upstream

Retain query parameters on redirect

---

pkg/download/buffer.go

If we do get a range header, even on a 200, we should use the range header to figure out the total size instead of the content-length. We are making this change because we are now seeing CAIOS returned values of 200s with content lengths that do not match the content range's total size.

Always use the range header if it's available
